[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_pastel_oracle_program = "AfP1c4sFcY1FeiGjQEtyxCim8BRnw22okNbKAsH2sBsB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
