[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.15"

[features]
resolution = false
skip-lint = false

[programs.localnet]
solana_pastel_oracle_program = "AfP1c4sFcY1FeiGjQEtyxCim8BRnw22okNbKAsH2sBsB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# build = "RUSTUP_TOOLCHAIN=nightly cargo build --release"
test = "sh scripts/run_tests_with_logs.sh"

